In [ ]:
import tensorflow as tf
import os
import matplotlib.pyplot as plt
from importlib import reload
import numpy as np
import skimage.io as sk_io

In [ ]:
import hyperparameterStudy.image_dataset as im_ds
reload(im_ds)
path = "/home/julius/dataspellprojects/oct-classifier/data/diabetic_images/test_files/retina_1536x2048x2045x2_30672.png"
my_ds = im_ds.ImageDataset(data_list=[(path, 1)], validation_split=False, mil=True)
images = np.squeeze(my_ds.train_data)

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import ImageGrid

fig = plt.figure(figsize=(24., 24.))
grid = ImageGrid(fig, 111,  # similar to subplot(111)
                 nrows_ncols=(10, 10),  # creates 2x2 grid of axes
                 axes_pad=0.1,  # pad between axes in inch.
                 )

for ax, im in zip(grid, range(images.shape[0])):
    # Iterating over the grid returns the Axes.
    ax.imshow(images[im, :, :], "gray")


plt.show()

In [47]:
import Visualization
reload(Visualization)
vis = Visualization.ImageVisualizer(results=np.expand_dims(np.array(list(range(100))), axis=1),
                              image_size=(1400, 1400),
                              instance_size=(140, 140, 10, 10),
                              background_image_path=path,
                              crop=(300 + 22, 300 + 24)
                              )
vis.plot_results_map()

In [48]:
a = np.array(list(range(100)))

In [13]:
import numpy as np
lala = np.ones((3, 3))

In [14]:
lala[:, 1] = 2



lala[:, 2] = 3



lala[2, :] = 4

In [16]:
lala.flatten()

array([1., 2., 3., 1., 2., 3., 4., 4., 4.])

In [9]:
lala = lala.flatten()
lala

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [17]:
lala.reshape(3, 3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [4., 4., 4.]])

In [18]:
for elem in lala:
    print(elem)

[1. 2. 3.]
[1. 2. 3.]
[4. 4. 4.]
